name = "FASTXDoReaders"
uuid = "a10097c8-9f5b-4030-a7d7-d11adc5c7381"
authors = ["JFdCD <jfdecd@icloud.com>"]
version = "1.0.0"

[deps]
FASTX = "c2308a5c-f048-11e8-3e8a-31650f418d12"

[compat]
FASTX = "2"
julia = "1.9"
